### ISSUE TITLE
Leading plus character is considered an error

### ISSUE THREAD

**Issue by Enrico204** [relvacode/iso8601#11]
By the ISO 8601, years after and including `0000` may be prefixed with the plus sign `+`. E.g., `+2007-00-00T00:00:00Z` is a valid date.

Trying to parse the date using this library results in a `UnexpectedCharactError`.

This problem occurs with v1.1.0. I wasn't able to test the v2.0.0 (due to known problem with go.mod).

**Comment by relvacode** [comment]
Released in https://github.com/relvacode/iso8601/releases/tag/v2.1.0

**Comment by Enrico204** [comment]
Thanks!
