### ISSUE TITLE
ParseString does not fail on invalid input string

### ISSUE THREAD

**Issue by Gaadek** [relvacode/iso8601#6]
As per the [documentation](https://pkg.go.dev/github.com/relvacode/iso8601?tab=doc#ParseString), ParseString parses an ISO8601 **compliant** date-time string into a time.Time object

However, if you try to parse an invalid string, e.g. `2020-02-30T10:24:54`, ParseString does not raise any error whereas the date is not valid.

You can test here: [https://play.golang.org/p/4fqmGeTsrjF](https://play.golang.org/p/4fqmGeTsrjF)

**Comment by relvacode** [comment]
Whilst I do not disagree with your sentiment, the ISO8601 library is purely for parsing the date from a string. The semantics of whether that date is valid is probably out of scope for this library as it would introduce extra complexity in handling leap years, etc.

I'm happy to introduce a standard library solution to this if you can find one.

**Comment by zaddok** [comment]
Im not sure a date parser should become involved in deciding which day of month numbers are valid. 

(Great library by the way, thanks!)

**Comment by rickb777** [comment]
I agree with the OP; this is the output from `time.Parse("2006-01-02T15:04:05.000-07:00", "2020-02-30T10:24:54.000+00:00")`

parsing time "2020-02-30T10:24:54.000+00:00": day out of range

I would expect `iso8601.Time` to give similar errors so it ca be a drop-in replacement.

**Comment by relvacode** [comment]
The point about equivalency to the standard library is a good one, and is a claim this library makes.

I've submitted a PR #9 which should implement this logic. Could someone take a look and give it a thumbs up? @rickb777 @Gaadek
